### ISSUE TITLE
Minor accumulated annoyances

### ISSUE THREAD

**Issue by samatechtw** [samatechtw/nx-vue3-vite#13]
This is an ongoing list of minor issues that don't interfere with critical operation, but would be nice to address.

- [x] Lint warning for `api.ts` response interceptor. Import Request type? Export type in `@sampullman/vue3-fetch-api`?
- [x] <strike>Generate `.eslintrc.js` instead of `.eslintrc.json` in app. Extremely minor/personal preference (`@nx-plus/vue` does it)</strike>
  - Fixed in #17 
- [ ] Figure out how to get Prettier to allow removing first level indent in `<template>`

**Comment by sampullman** [comment]
I have given up on the last task 😅
