### ISSUE TITLE
Option `docs` is required, but not in document.

### ISSUE THREAD

**Issue by apolkingg8** [samatechtw/nx-vue3-vite#31]
https://github.com/samatechtw/nx-vue3-vite/blob/0b19e1efa0d94fc5f831bdd15acb5a878eb084bd/packages/vue3-vite/src/executors/build-docs/executor.ts#L14

The `options.docs` is a required argument, but not documented.

**Comment by samatechtw** [comment]
Renamed the docs option to "root" to match the related generator option name. Not tested on a real project yet, so leaving open until confirmed.

**Comment by samatechtw** [comment]
There's another related issue that will be covered here - the `dist` option is not respected for the build executor.

**Comment by samatechtw** [comment]
Confirmed deploy via `nx build <docs-app>` is working.
