### ISSUE TITLE
tsconfig path updates

### ISSUE THREAD

**Issue by samatechtw** [samatechtw/nx-vue3-vite#35]
Currently, we include Vite and tsconfig paths for convenient local imports, e.g. `@app/` and `@assets/`. In a large Nx project this becomes unwieldy, since tsconfig paths arrays are not merged with `tsconfig.base.json`. We end up needing to duplicate all paths in `tsconfig.app.json` as well as `vite.config.ts`.

We'll either need to switch to relative imports in the app, or use paths from `tsconfig.base.json`. To alleviate the burden of manually including each path in `vite.config.ts`, we can do something like:

```ts
import tsconfigBase from '../../tsconfig.base.json'

const resolve = (p: string) => path.resolve(__dirname, p)

const tsconfigBaseAliases = (rootOffset: string): Record<string, string> => {
  const paths = tsconfigBase.compilerOptions?.paths || []
  const aliases: Record<string, string> = {}
  for (const [name, path] of Object.entries(paths)) {
    aliases[name] = resolve(`${rootOffset}/${path}`)
  }
  return aliases
}

export default defineConfig({
  resolve: {
    alias: {
      ...tsconfigBaseAliases('../..'),
    },
  },
}
```

**Comment by realityfilter** [comment]
+1 This should be in the vite.config.ts template.

**Comment by fvanwijk** [comment]
If I have a lib that is imported in an app, how to resolve @lib aliases?

Example:
app: `component-example`
lib: `component`

In `component-example`: `import { Child } from '@xx/component'` // There is an absolute alias and it works correctly
In `component`: `import { Child } from '@lib/components/Child.vue';` // This should be a relative alias to the project root of Child. How?

First thing I noticed is that you need an alias for `@lib` in `example-component/vite.config.ts` to resolve the import in `component`. That is very confusing.
I like to have aliases relative to the imported file that has an import, not to the project that is served.

**Comment by sampullman** [comment]
Sorry this one is taking a while to resolve - in our projects we're sharing the `tsconfigBaseAliases` function in a shared library (e.g. `util-vite-config`). I think it's not ideal to include it in the template for this reason. A downside to the library approach is that it has to use a relative import, since TS paths aren't working in `vite.config.ts`. One solution might be to move the function to a separate NPM package.

For reference, here's how we do it:

```ts
// vite.config.ts
import { tsconfigBaseAliases } from '../../libs/web/util-vite-config/src'

export default defineConfig({
  resolve: {
    alias: {
      '@theme/': `${resolve('../../libs/web/ui-theme/src')}/`,
      ...tsconfigBaseAliases(),
    },
  },
}
```

```ts
// util-vite-config.ts
import path from 'path'
import tsconfigBase from '../../../../../tsconfig.base.json'

const rootOffset = '../../../../../'

const resolve = (p: string) => path.resolve(__dirname, p)

export const tsconfigBaseAliases = (): Record<string, string> => {
  const paths = tsconfigBase.compilerOptions?.paths || []
  const aliases: Record<string, string> = {}
  for (const [name, path] of Object.entries(paths)) {
    const simplePath = path[0].replace('/*', '/')
    const relative = `${rootOffset}${simplePath}`
    if (name.includes('/*')) {
      const resolved = `${resolve(relative)}/`
      aliases[name.replace('/*', '/')] = resolved
    } else {
      aliases[name] = resolve(relative)
    }
  }
  return aliases
}
```

Maybe it's best to add an optional flag that includes it during app generation.

@fvanwijk I don't have a good solution to your problem, we just try to keep libraries small and only use relative imports. I agree that it's a pain.

**Comment by merlosy** [comment]
Hi! Maybe this lib can do the trick? https://www.npmjs.com/package/vite-tsconfig-paths
