### ISSUE TITLE
Vitest instead of jest

### ISSUE THREAD

**Issue by d-koppenhagen** [samatechtw/nx-vue3-vite#44]
As Vue3 became the default when setting up new vue.ja apps, and with the current very fast evolvement of and vitest, some of the recommendations changed.

The vue3 docs are now clearly recommending to use vitest instead of jest as the unit testing library when working with vite:
https://vuejs.org/guide/scaling-up/tooling.html#testing

My suggestion is, to provide vitest support as a default but keep jest as optional implementation to support both.

**Comment by sampullman** [comment]
Thank you for the issue, and sorry for the late reply. A few month packs I experimented with Vitest integration and ran into some problems. There have been quite a few releases since then, so we'll give it another try.
