### ISSUE TITLE
Jest does not support TS specs

### ISSUE THREAD

**Issue by fvanwijk** [samatechtw/nx-vue3-vite#45]
`nx g nx-vue3-vite:app xxx` generates a new app. First thing I notice is that there is a jest.config.ts and a jest.config.js with different config.

It looks like only the JS file is used.
In the ts file there is `'^.+\\.vue$': './deps/vue3-jest',` and this seems invalid; there is no './deps' dir. (Addressed in #34)

If I add an empty test that uses an `import`, I get the error:

> Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

This removes the error:
1. Remove the jest.config.js
2. Change the extension of jest.config.ts to js
3. `npm i @vue/vue3-jest`
4. Replace the vue transform with `'^.+\\.vue$': '@vue/vue3-jest',`

For generated apps, but not for libs (??), then this error appears:
> Property 'toEqual' does not exist on type 'Assertion'.

I'd like some improvements on the generated apps and libs that Jest is setup properly with TS support.

**Comment by sampullman** [comment]
The generator should work with TS specs now, I added an example to the app generator. Ideally there would be a flag to select the test method (vue3-jest/vitest/cypress component).
