### ISSUE TITLE
Upgrade to Vite 3.x

### ISSUE THREAD

**Issue by thijslimmen** [samatechtw/nx-vue3-vite#55]
Vite 3.0 is out! Would be nice to update :)

https://vitejs.dev/blog/announcing-vite3.html

**Comment by sampullman** [comment]
Good call, I will take a look at this soon. The only thing I'm not sure about is whether to include [@vitejs/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) by default.

**Comment by thijslimmen** [comment]
Personally, I think this package should be compatible with vite 2.x and 3.x to be backward compatible? Because there seem to be no vite configuration changes.

```json
dependencies: {
   "vite":  "2.9.14^ | 3.x.x^"
}
```

I think this legacy package is only there to support legacy frameworks/browsers in order to generate polyfills, etc.? This is not the purpose of this `nx-vue3-vite` package.

**Comment by sampullman** [comment]
For the executors that's true, there shouldn't be any issue with 3.x support. I meant whether the legacy plugin should be included in the generator.

**Comment by thijslimmen** [comment]
I don't think it needs to be included
