### ISSUE TITLE
serve executor process sometimes leaks

### ISSUE THREAD

**Issue by sampullman** [samatechtw/nx-vue3-vite#60]
Occasionally the dev server executor doesn't get stopped correctly, leading to issues when it's restarted:

```
Running Vite Dev server: http://localhost:8080
  mode = development
Port 8080 is in use, trying another one...
Port 8081 is in use, trying another one...
```

It seems more common if the server did a full refresh, maybe something changed in the Vite3 update. The current workaround is to find and kill the node process manually.

**Comment by sampullman** [comment]
This may be an Nx bug: https://github.com/nrwl/nx/issues/12708

**Comment by AgentEnder** [comment]
This is unrelated to the linked Nx issue, as the Nx daemon doesn't use a port.

**Comment by sampullman** [comment]
That makes sense, but the linked issue indicates that an executor child process is kept alive, not just the daemon. Is that intended behavior?

I will try to pinpoint what's happening tomorrow, so far I'm only certain that:
- Usually when the `serve` executor is killed manually, only the daemon stays alive
- Occasionally when the `serve` executor is killed, the daemon/executor/child processes stay alive

It could be related to Vite, but looks pretty similar to the linked issue.

**Comment by AgentEnder** [comment]
Executors are responsible for handling cleanup of any child processes they spawn, this would be unrelated to Nx's side.

**Comment by sampullman** [comment]
Oh, I misread the linked issue, I thought the executor process was alive after the user ctrl-c'd. This is probably a change in behavior between Vite2 and Vite3. Thanks for following up!

**Comment by sampullman** [comment]
After major version bumps in Vite & Nx, I'm not noticing this problem anymore.
