### ISSUE TITLE
Make library generator work better with Vite 4 (also some bugs)

### ISSUE THREAD

**Issue by abemscac** [samatechtw/nx-vue3-vite#68]
- App generator still shows `[NX] Cannot find module '@nrwl/jest'`.
  - This is solved after manually install `@nrwl/jest`.
- App generator shows `[NX] Cannot convert undefined or null to object`.
  - ~This is solved after removing `@nrwl/jest` from `ProjectDevDependencies`.~
  - The cause is that `dependencies` is being removed from `package.json` after `npm install`. Manually added it back fixed the issue.
- Library generator shows `[NX] Cannot find module 'typescript'`.
  - ~This is solved after removing `typescript` from `LibraryDevDependencies `.~
  - The cause is that `dependencies` is being removed from `package.json` after `npm install`. Manually added it back fixed the issue.

~By the way, I've pushed a branch starts with name  `111-make...` that tries to add path to `tsconfig.base.json`.
The add-path-part seems to work, but when I tried to use it in another repo, TypeScript failed to recognize the created library when I `import { ... } from '@{npmScope}/some/library`. The `npmScope` is from `nx.json`.~
- We use project paths (`paths` in `tsconfig.json` in individual project) instead of workspace paths (`paths` in `tsconfig.base.json`), so no need to add path in `tsconfig.base.json`.

As for `workspace.json`, it seems that Nx already handled that part for us while creating a library.

**Comment by abemscac** [comment]
Hi @sampullman 

Is it correct to say that eventually, we'll have to move asset-files from `apps/{app}/assets` to `libs/assets`, so that the requirements in #35 can be fulfilled?
If yes, I think the app generator will also generate related libs.
DidI misunderstand anything? 🤔

**Comment by sampullman** [comment]
Sorry for the late reply!

Both apps and libs can have assets, depending on how each project wants to set up their build system. #35 is about a hacky workaround for using any path defined in tsconfig in a Vite project. Vite doesn't recognize the folder structure correctly by default, so it can't handle something like `@samatech/frontend/api`. We need to tell it where libs are with the `alias` config option in `vite.config.ts` (I haven't double checked this in a while though, maybe it's fixed in Vite!)

**Comment by abemscac** [comment]
I see, I have a couple more questions:

1. Do we still want `assets` folder to be placed inside each individual app&library like `apps/myapp/src/assets/` and `libs/mylib/src/assets`, or we only want one `assets` folder such as `libs/assets`?
2. Do we wan to use the `paths` in `tsconfig.json` (let's call it local paths, I don't know what's the correct terms)  instead of the one in `tsconfig.base.json` (and let's just call it global paths)? My understanding is they don't work with each other; only one of them can be used for each app&library at the same time, is that correct?
3. If we were to use local paths, is it correct to say that in integrated repo, we will not be able to import assets from different projects (i.e. import the assets in `libs/mylib` from `apps/myapp`)?
4. If we were to use global paths, and each project has its own `assets` folder, do we need to create paths for these folders? For example, `@apps/myapp/assets` and `@libs/mylib/assets`?

**Comment by sampullman** [comment]
> 1. Do we still want assets folder to be placed inside each individual app&library like apps/myapp/src/assets/ and libs/mylib/src/assets, or we only want one assets folder such as libs/assets?

Good question. The app should still have an asset folder, but I'm not sure about libs. I wonder if there should be multiple kinds of lib generators (or an enum option in the current lib generator). We separate assets/components into their own libs in our project, so it's useful to be able to generate an "assets" lib, vs a "components" or "types" lib. For now, I think it's ok to leave out the assets folder in the lib generator though, I'm not sure everyone will want it.

> 2. Do we wan to use the paths in tsconfig.json (let's call it local paths, I don't know what's the correct terms) instead of the one in tsconfig.base.json (and let's just call it global paths)? My understanding is they don't work with each other; only one of them can be used for each app&library at the same time, is that correct?

That's my understanding too, we can only use paths in `tsconfig.base.json`. If you include `paths` in the local tsconfig, it will override the base paths.

> 3. If we were to use local paths, is it correct to say that in integrated repo, we will not be able to import assets from different projects (i.e. import the assets in libs/mylib from apps/myapp)?

Yes, although it's possible (but bad) to reference other libs with a relative path (e.g. `../../libs/mylib` from `apps/myapp`)

> 4. If we were to use global paths, and each project has its own assets folder, do we need to create paths for these folders? For example, @apps/myapp/assets and @libs/mylib/assets?

I don't think we should provide a paths entry specifically for assets, just for the lib. Each lib is a module with an `index.ts`, which is pointed to by the path. In some of our projects we do `"@ui-assets/*": ["libs/web/ui-assets/src/*"]` as shorthand, but that probably shouldn't be done automatically by the generator.
