### ISSUE TITLE
Nx v16 support

### ISSUE THREAD

**Issue by joshvanallen** [samatechtw/nx-vue3-vite#90]
As part of Nx v16, there's new scoped packages for Nx now. Instead of `@nrwl/*`, they are all under `@nx/*` now. `@nrwl/*` may still work as it's just exporting `@nx/*`, it's just better to work on migrating to it. Nx v17 will no longer publish `@nrwl/*`.

Here's that documentation: https://nx.dev/recipes/other/rescope.

**Comment by sampullman** [comment]
Thanks for the heads up! I'll take care of this with the next round of package updates.
