### ISSUE TITLE
@nx/vite:test executor error with relative path config settings

### ISSUE THREAD

**Issue by rizypb** [samatechtw/nx-vue3-vite#91]
Here is the project.json config for a Vue 3 based frontend app in my monorepo:
```
    "test": {
      "executor": "@nx/vite:test",
      "outputs": ["coverage/libs/e2e/apps"],
      "options": {
        "config": "apps/admin/vite.config.ts",
        "passWithNoTests": true
      }
    }
```
``vite.config.ts`` is located in the root of the Vue 3 app.

When I run this executor command:
```
nx run admin:test --ci --code-coverage
```
Then it throws the following error:
```
✘ [ERROR] Could not resolve "/Users/user/Documents/projects/next-api/apps/admin/apps/\admin/vite.config.ts"
failed to load config from /Users/user/Documents/projects/next-api/apps/admin/apps/admin/vite.config.ts
 >  NX   Build failed with 1 error:
   error: Could not resolve "/Users/user/Documents/projects/next-api/apps/admin/apps/admin/vite.config.ts"
   Pass --verbose to see the stacktrace.
```
If I change the config path to this: ``"config": "vite.config.ts"`` then it throws the following error:
```
✘ [ERROR] Could not resolve "/Users/user/Documents/projects/next-api/vite.config.ts"
failed to load config from /Users/user/Documents/projects/next-api/vite.config.ts
 >  NX   Build failed with 1 error:
   error: Could not resolve "/Users/user/Documents/projects/next-api/vite.config.ts"
   Pass --verbose to see the stacktrace.
```
I am not sure why these errors are happening as the config path seems correct in the ``project.json`` file. Ideally it should pick the ``vite.config.ts`` file from this path:  ``/Users/user/Documents/projects/next-api/apps/admin/vite.config.ts``

Any idea what I missed in the config? Please advise, thanks.

**Comment by sampullman** [comment]
I don't think anything in this plugin could be affecting the behavior of the `@nx/vite:test` executor. Maybe this is the same error you're experiencing: https://github.com/nrwl/nx/issues/16985

**Comment by rizypb** [comment]
I think you are correct @sampullman

**Comment by i-bajrai** [comment]
Should this be closed as a duplicate?

**Comment by rizypb** [comment]
> Should this be closed as a duplicate?

Yes please
