### ISSUE TITLE
Cypress as optional Peer dependency

### ISSUE THREAD

**Issue by Mararok** [samatechtw/nx-vue3-vite#97]
Can you set `cypress` and `@cypress/vite-dev-server` as optional peerDependencies ?

Currently when project don't use cypress, yarn giving me a warning:
```
doesn't provide @cypress/vite-dev-server (p117c2), requested by nx-vue3-vite.
doesn't provide cypress (p12b4c), requested by nx-vue3-vite.
```

To fix it you can add to package.json(*in build output package.json):
```json
"peerDependenciesMeta": {
    "cypress": {
      "optional": true
    },
    "@cypress/vite-dev-server": {
      "optional": true
    }
},
```

**Comment by sampullman** [comment]
Sure, I can do that in the next round of package updates.
